@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Mon Jul 08 00:33:55 +0800 2024
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
=======
REM Generated by Vivado on Mon Jul 08 01:22:24 +0800 2024
REM SW Build 2018833 on Wed Oct  4 19:58:22 MDT 2017
>>>>>>> 1d7a6718f1be1547d29186d048df26809c52359c
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
echo "xvlog --incr --relax -prj tb_top_vlog.prj"
call xvlog  --incr --relax -prj tb_top_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
